# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minitwitter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11minitwitter.proto\x12\x0e\x63lient_message\x1a\x1bgoogle/protobuf/empty.proto\"\x17\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\x12GetMessagesRequest\x12\t\n\x01n\x18\x01 \x01(\x05\"@\n\x13GetMessagesResponse\x12)\n\x08messages\x18\x01 \x03(\x0b\x32\x17.client_message.Message2\xa5\x01\n\x0bMiniTwitter\x12>\n\x0bSendMessage\x12\x17.client_message.Message\x1a\x16.google.protobuf.Empty\x12V\n\x0bGetMessages\x12\".client_message.GetMessagesRequest\x1a#.client_message.GetMessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minitwitter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=66
  _globals['_MESSAGE']._serialized_end=89
  _globals['_GETMESSAGESREQUEST']._serialized_start=91
  _globals['_GETMESSAGESREQUEST']._serialized_end=122
  _globals['_GETMESSAGESRESPONSE']._serialized_start=124
  _globals['_GETMESSAGESRESPONSE']._serialized_end=188
  _globals['_MINITWITTER']._serialized_start=191
  _globals['_MINITWITTER']._serialized_end=356
# @@protoc_insertion_point(module_scope)
